<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Session 1 PHP</title>
</head>
<style>


    *{
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }
    body{
        background-color: #51e2f5;
    }
    .container{
        max-width: 80%;
        background-color: royalblue;
        color: yellow;
        margin: auto;
        padding: 23px;
        text-align: center;
    }
    h1{
        color: greenyellow;
    }
    h2{
        color: pink;
    }


</style>




<body>
    <h1>First Session Of Php</h1>


    <h3>writing our first code in php</h3>
    <?php

    // here is writing our first php code

    echo ("hello world! welcome to php.</br>");
    echo ("this is second line of php.</br>");

    // now here i declare our variable in php 

    $newVar = "this is string is in saved in a variable namely newVar";
    echo $newVar;
    echo "<br>";

    // find out data type in php by using following procedure 

    $a = "hello dear i am here";
    $b = 123;
    $c = 99.123;
    $d = true;

    echo var_dump($a)."<br>";
    echo var_dump($b)."<br>";
    echo var_dump($c)."<br>";
    echo var_dump($d)."<br>";

    // now here we use arithmetic operators 

    $val1 = 10;
    $val2 = 5;

    echo "the sum of val1 and val2 is ".($val1+$val2)."<br>";
    echo "the subtraction of val1 and val2 is ".($val1-$val2)."<br>";
    echo "the multiplication of val1 and val2 is ".($val1*$val2)."<br>";
    echo "the division of val1 and val2 is ".($val1/$val2)."<br>";
    ?>





    <div class="container">
        <h1>Here Mr. Muhammad Scharique Najam Ansari Learning About PHP</h1>
        <br><br>
        
        <?php 

        // if else statements in php 
        echo"<h2>IF & ELSE STATEMENTS IN PHP</h2>.<br>";
        echo"<h3>your riding status is here</h3>";
        $age = 17;
        if($age>18){
            echo ("you can ride a bike");
        }
        elseif ($age==17) {
            echo ("you can try to ride a bike only for testing purpose");
        }
        else{
            echo("you can not ride a bike");
        };

        echo "<br> <br> <br>";

        // array in php 

        echo"<h2>ARRAYS IN PHP</h2>";

        $languages = array("C++", "Python", "NodeJS", "Php");
        // to print full length of array 
        print_r($languages);

        echo "<br>";
        echo $languages[2];

        echo "<br> <br>";

        // here we learn about count in array 
        echo"<h2>Learn about count of array </h2>";
        echo "<br>";

        echo count($languages);

        echo "<br>";

        
        $items = array("rice", "wheat", "lentils", "milk", "bread", "eggs", "sugar", "salt", "oil", "ghee");
        echo $items[2];
        echo "<br> <br>";


        // loops in php 
        // while loop in php 

        echo"<h2>WHILE LOOP IN PHP</h2>";
        echo "<br><br<";
        $a = 0;
        while ($a <= 10) {
            echo "<br>The value of a in While Loop is: ";
            echo $a;
            $a++;
        }

        echo"<br><br>";
        echo "<h2>LOOP OF ARRAY LENGTH VIA WHILE LOOP IN PHP</h2>";
        echo "<br>";
        $a = 0;
        while ($a < count($languages)) {
            echo "<br>The value of languages in While Loop is: ";
            echo $languages[$a];
            $a++;
        }

        echo "<br> <br>";


        // do while loop in php 
        echo "<h2>DO WHILE LOOP IN PHP</h2>";
        echo "<br>";
        $a = 0;
        do  {
            echo "<br>The value of a in Do While Loop is: ";
            echo $a;
            $a++;
        }
        while ($a < 10);

        echo "<br> <br> <br>";


        // For Loop in php 
        echo "<h2>FOR LOOP IN PHP</h2>";
        echo "<br>";

        for ($i=0; $i < count ($items) ; $i++) { 
            echo "<br> The value of our item is in for loop:  ";
            echo $items[$i];
        }

        echo "<br><br>";
        
        echo "<h2>PRINT TABLE OF 2 VIA FOR LOOP IN PHP</h2>";
        echo "<br>";
        for ($i=1; $i <=10 ; $i++) { 
            echo "2 * " . $i . " = " . (2 * $i) . "<br>";
        }

        echo "<br>";
        // for each loop in php 
        echo "<h2>PRINT AN ARRAY IN FOR EACH LOOP</h2>";
        echo "<br>";

        foreach ($languages as $value) {
            echo "<br> the value of languages in ForEach Loop is: ";
            echo $value;
        }
        echo "<br><br><br>";

        // functions in php 

        echo "<h2>HERE WE CREATE A FUNCTION IN PHP</h2>";
        echo "<br>";

        function name(){
            echo "This function is generated by Mr. Muhammad Scharique Najam Ansari";
        }
        name();




        ?>
    </div>


    
    
</body>
</html>